/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/pipeline/velocity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stage velocity
         * @description Average days contacts spend in each stage before moving on, derived from the gaps between consecutive status_events. Contacts with a single recorded event contribute nothing, since no dwell interval exists.
         */
        get: operations["velocity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StageVelocity: {
            /** @enum {string} */
            fromStage?: "CONTACTED" | "APPLIED" | "INTERVIEWING" | "OFFER" | "REJECTED";
            /** @enum {string} */
            toStage?: "CONTACTED" | "APPLIED" | "INTERVIEWING" | "OFFER" | "REJECTED";
            avgDays?: number;
            /** Format: int64 */
            transitions?: number;
        };
        VelocityReport: {
            stages?: components["schemas"]["StageVelocity"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    velocity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VelocityReport"];
                };
            };
        };
    };
}
