// Arch Board scenario library. 100 default scenarios grouped by category,
// all solvable with the NODE_TYPES palette in arch.js (see Scenario typedef there).
// Variety comes from domain framing, budgets, and check weighting — the same
// way real interviews re-skin a dozen core topologies.

/** @typedef {import("./arch.js").Check} Check */
/** @typedef {import("./arch.js").Scenario} Scenario */

/** @returns {Check} */
const node = (type, label, points) => ({ kind: "node", type, label, points });
/** @returns {Check} */
const edge = (from, to, label, points) => ({ kind: "edge", from, to, label, points });
/** @returns {Check} */
const biEdge = (from, to, label, points) => ({ kind: "edge", from, to, bidi: true, label, points });

export const SCENARIO_CATEGORIES = [
  "Commerce",
  "Fintech",
  "Social",
  "Realtime",
  "Content & Media",
  "Data & Analytics",
  "Infrastructure",
  "Mobility & Logistics",
  "Gaming",
  "B2B SaaS",
];

const COMMERCE = [
  {
    id: "catalog",
    category: "Commerce",
    name: "Read-heavy product catalog",
    brief:
      "Millions of reads, few writes. Serve product pages fast and cheap worldwide without melting the database.",
    budget: 11,
    checks: [
      node(["client"], "A client browses the catalog", 5),
      node(["cdn"], "A CDN exists for static assets", 10),
      edge(["client"], ["cdn"], "Clients fetch static assets from the CDN", 10),
      edge(["client", "cdn"], ["lb", "gateway"], "API traffic is load-balanced", 10),
      edge(["lb", "gateway"], ["service"], "A stateless API tier serves catalog reads", 10),
      node(["cache"], "Hot reads come from a cache", 15),
      edge(["service"], ["cache"], "The service reads cache-aside", 15),
      edge(["service"], ["sql", "nosql"], "The source of truth lives in a database", 15),
      node(["monitor"], "Latency and error budgets are observable", 10),
    ],
    warnings: [
      {
        when: ({ hasNode }) => !hasNode(["cdn"]),
        text: "Every image and JS bundle ships from origin — a CDN is the cheapest win available here.",
      },
    ],
  },
  {
    id: "flashsale",
    category: "Commerce",
    name: "Flash-sale ticket burst",
    brief:
      "Spiky traffic: 100× normal load for 10 minutes when sales open. Don't oversell inventory, don't fall over, and keep the queue of buyers fair.",
    budget: 14,
    checks: [
      node(["client"], "A client tries to buy", 5),
      edge(["client"], ["lb", "gateway"], "Traffic enters through a load balancer or gateway", 10),
      edge(["lb", "gateway"], ["service"], "Stateless services absorb the burst horizontally", 10),
      node(["queue"], "A queue buffers purchase requests instead of dropping them", 15),
      edge(["service"], ["queue"], "The service enqueues purchases for ordered processing", 10),
      biEdge(["queue"], ["worker"], "Workers drain the queue at a sustainable rate", 10),
      node(["cache"], "Inventory counts served from a cache, not the DB", 10),
      edge(["service"], ["cache"], "The service checks availability against the cache", 10),
      edge(["worker", "service"], ["sql", "nosql"], "Orders are persisted durably", 10),
      node(["monitor"], "You can see the spike happening in real time", 10),
    ],
    warnings: [
      {
        when: ({ hasNode, hasEdge }) => hasNode(["service"]) && hasEdge(["service"], ["sql", "nosql"]) && !hasNode(["queue"]),
        text: "Synchronous writes straight to the database — at 100× load this is where it falls over. Buffer through a queue.",
      },
    ],
  },
  {
    id: "cart-checkout",
    category: "Commerce",
    name: "Cart & checkout flow",
    brief:
      "Carts must survive device switches and node restarts; checkout converts a cart into an order exactly once, even on a double-click.",
    budget: 14,
    checks: [
      node(["client"], "A client shops with a cart", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a gateway or load balancer", 10),
      node(["auth"], "Checkout requires an authenticated session", 10),
      edge(["gateway", "lb", "auth"], ["service"], "A cart/checkout service owns the flow", 10),
      node(["cache"], "Active carts live in a fast shared store", 15),
      edge(["service"], ["cache"], "The service reads and writes carts in the cache", 10),
      edge(["service"], ["queue"], "Order placement is enqueued for exactly-once processing", 10),
      biEdge(["queue"], ["worker"], "Workers turn carts into orders", 10),
      edge(["worker", "service"], ["sql"], "Orders are committed to a transactional store", 15),
      node(["monitor"], "Conversion and error rates are visible", 5),
    ],
  },
  {
    id: "inventory-sync",
    category: "Commerce",
    name: "Warehouse inventory sync",
    brief:
      "Thousands of stock updates per minute from warehouses; product pages must not show phantom stock for more than a few seconds.",
    budget: 13,
    checks: [
      node(["client"], "Warehouse systems push stock updates", 5),
      edge(["client"], ["gateway", "lb"], "Updates enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An ingest service validates updates", 10),
      node(["queue"], "Updates are buffered for ordered application", 15),
      edge(["service"], ["queue"], "The service enqueues instead of writing inline", 10),
      biEdge(["queue"], ["worker"], "Workers apply updates at a steady rate", 10),
      edge(["worker"], ["sql"], "Stock truth is applied transactionally", 15),
      edge(["worker"], ["cache"], "The read cache is refreshed on every change", 15),
      node(["monitor"], "Warehouse-to-site lag is measured", 10),
    ],
  },
  {
    id: "search-suggest",
    category: "Commerce",
    name: "Search autocomplete",
    brief:
      "Sub-50ms prefix suggestions on every keystroke. The database can't be allowed to see this traffic.",
    budget: 10,
    checks: [
      node(["client"], "A client types in the search box", 5),
      edge(["client"], ["gateway", "lb"], "Keystroke traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "A suggestion service answers", 10),
      node(["cache"], "Suggestions are served from memory", 20),
      edge(["service"], ["cache"], "The hot path reads only the cache", 15),
      edge(["service"], ["nosql", "sql"], "The index source of truth lives in a database", 10),
      node(["worker"], "The index is rebuilt asynchronously", 10),
      edge(["worker"], ["nosql", "sql"], "Workers write the rebuilt index", 10),
      node(["monitor"], "p99 latency is watched", 10),
    ],
  },
  {
    id: "reviews",
    category: "Commerce",
    name: "Reviews & ratings",
    brief:
      "Read-heavy reviews with an abuse problem: every submission passes moderation before it's visible, without blocking the submitter.",
    budget: 13,
    checks: [
      node(["client"], "A client reads and writes reviews", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A review service owns reads and submissions", 10),
      edge(["service"], ["queue"], "Submissions are enqueued for moderation", 15),
      biEdge(["queue"], ["worker"], "Moderation workers consume the queue", 10),
      edge(["worker"], ["sql", "nosql"], "Approved reviews are persisted", 10),
      node(["cache"], "Hot product review pages are cached", 10),
      edge(["service"], ["cache"], "Reads hit the cache first", 10),
      edge(["service"], ["sql", "nosql"], "The service reads the durable store on miss", 10),
      node(["monitor"], "Moderation backlog is observable", 10),
    ],
  },
  {
    id: "promo-codes",
    category: "Commerce",
    name: "Promo code validation",
    brief:
      "Checkout validates promo codes at peak traffic; limited-use codes must never exceed their cap under concurrency.",
    budget: 12,
    checks: [
      node(["client"], "A client applies a code at checkout", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A promo service validates codes", 10),
      node(["cache"], "Code lookups come from memory", 15),
      edge(["service"], ["cache"], "Validation reads the cache", 10),
      node(["queue"], "Redemptions are serialized to enforce usage caps", 10),
      edge(["service"], ["queue"], "The service enqueues redemptions", 10),
      biEdge(["queue"], ["worker"], "A single consumer applies redemptions in order", 5),
      edge(["worker", "service"], ["sql"], "Redemption counts live in a transactional store", 15),
      node(["monitor"], "Redemption rates and cap breaches are visible", 10),
    ],
  },
  {
    id: "order-tracking",
    category: "Commerce",
    name: "Order tracking page",
    brief:
      "Carriers push status webhooks in bursts; customers refresh the tracking page constantly. Neither side should feel the other's latency.",
    budget: 13,
    checks: [
      node(["client"], "Customers watch the tracking page", 5),
      edge(["client"], ["gateway", "lb"], "Both webhooks and reads enter through the edge", 10),
      edge(["gateway", "lb"], ["service"], "A tracking service fronts the data", 10),
      edge(["service"], ["queue"], "Carrier webhooks are buffered, not processed inline", 15),
      biEdge(["queue"], ["worker"], "Workers apply status events", 10),
      edge(["worker"], ["nosql", "sql"], "Status history is appended durably", 15),
      node(["cache"], "The latest status is cached for the read path", 15),
      edge(["service"], ["cache"], "Page reads come from the cache", 10),
      node(["monitor"], "Webhook lag is measured", 10),
    ],
  },
  {
    id: "recs-widget",
    category: "Commerce",
    name: "You-may-also-like widget",
    brief:
      "Personalized recommendations on every product page. Computing them online is too slow — serve precomputed lists fast.",
    budget: 12,
    checks: [
      node(["client"], "Every product page requests recommendations", 5),
      edge(["client"], ["gateway", "lb"], "Traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "A recommendation service serves lookups", 10),
      node(["worker"], "Recommendations are precomputed offline", 15),
      edge(["worker"], ["nosql", "sql"], "Precomputed lists are stored for lookup", 10),
      node(["cache"], "Hot lists are cached in memory", 15),
      edge(["service"], ["cache"], "The hot path reads the cache", 15),
      edge(["service"], ["nosql", "sql"], "Cache misses fall back to the store", 10),
      node(["monitor"], "Hit rate and staleness are tracked", 10),
    ],
  },
  {
    id: "subscription-billing",
    category: "Commerce",
    name: "Subscription renewals",
    brief:
      "Monthly renewals charge thousands of cards in a nightly window; failures retry with backoff and never double-charge.",
    budget: 17,
    checks: [
      node(["client"], "Customers manage their subscriptions", 5),
      node(["auth"], "Card management is authenticated", 5),
      node(["psp"], "Charges go through a payment provider", 15),
      node(["queue"], "Renewals are enqueued, not fired in a loop", 15),
      biEdge(["queue"], ["worker"], "Workers drain renewals at a controlled rate", 10),
      edge(["worker"], ["psp"], "Workers own the charge calls and retries", 15),
      edge(["psp"], ["service", "worker", "queue"], "Provider webhooks confirm asynchronously", 10),
      edge(["worker", "service"], ["sql"], "Billing state is durable and idempotent", 15),
      node(["monitor"], "Failed renewals page someone", 10),
    ],
  },
];

const FINTECH = [
  {
    id: "payment",
    category: "Fintech",
    name: "Payment end-to-end",
    brief:
      "Design checkout payment processing: accept a payment, call the provider, survive retries and webhooks, and keep records consistent. Card data must never touch your own database.",
    budget: 16,
    checks: [
      node(["client"], "A client initiates checkout", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a gateway or load balancer — clients never hit services directly", 10),
      node(["auth"], "Authentication sits in front of money movement", 10),
      edge(["gateway", "lb", "auth"], ["service"], "Requests are routed to a payment service", 10),
      edge(["service"], ["psp"], "The service calls the payment provider — your servers own that integration", 15),
      edge(["psp"], ["service", "worker", "queue"], "A webhook path back from the provider for async confirmations and disputes", 15),
      node(["queue"], "A queue decouples confirmation and reconciliation work", 10),
      biEdge(["queue"], ["worker"], "Workers consume from the queue", 10),
      edge(["service", "worker"], ["sql", "nosql"], "Payment state is persisted durably", 10),
      node(["monitor"], "Observability on the money path", 5),
    ],
    warnings: [
      {
        when: ({ hasEdge }) => hasEdge(["client"], ["psp"]),
        text: "The client integrates the payment provider directly — API secrets belong on the server, and you lose the ability to record the attempt.",
      },
      {
        when: ({ hasNode }) => !hasNode(["sql", "nosql"]),
        text: "Nowhere durable to store payment state — reconciliation against the provider becomes impossible.",
      },
    ],
  },
  {
    id: "ledger",
    category: "Fintech",
    name: "Double-entry ledger",
    brief:
      "Every money movement writes two entries that must balance. Order matters; eventual consistency is not acceptable on the write path.",
    budget: 12,
    checks: [
      node(["client"], "A client triggers money movements", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      node(["auth"], "Money movement is authenticated", 10),
      edge(["gateway", "lb", "auth"], ["service"], "A ledger service owns the API", 10),
      node(["queue"], "Writes are serialized for strict ordering", 15),
      edge(["service"], ["queue"], "The service enqueues entries", 10),
      biEdge(["queue"], ["worker"], "A single-writer consumer applies entries", 10),
      edge(["worker"], ["sql"], "Balanced entries commit transactionally to SQL", 20),
      node(["monitor"], "Balance drift alerts immediately", 10),
    ],
    warnings: [
      {
        when: ({ hasEdge }) => hasEdge(["service", "worker"], ["nosql"]),
        text: "A ledger on eventually-consistent storage — balance invariants need real transactions.",
      },
    ],
  },
  {
    id: "fraud-screening",
    category: "Fintech",
    name: "Inline fraud screening",
    brief:
      "Score every transaction in under 100ms inline, and run deeper analysis async. Blocking checkout on the deep path is not an option.",
    budget: 15,
    checks: [
      node(["client"], "A client submits a transaction", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      node(["auth"], "Transactions are authenticated", 5),
      edge(["gateway", "lb", "auth"], ["service"], "A scoring service sits inline", 10),
      node(["cache"], "Feature-store reads come from memory", 15),
      edge(["service"], ["cache"], "Inline scoring reads only the cache", 10),
      edge(["service"], ["queue"], "Deep analysis is fanned out asynchronously", 10),
      biEdge(["queue"], ["worker"], "Analysis workers consume the stream", 10),
      edge(["worker"], ["sql", "nosql"], "Verdicts and features are persisted", 10),
      node(["monitor"], "Fraud rates are watched in real time", 15),
    ],
  },
  {
    id: "payouts",
    category: "Fintech",
    name: "Nightly seller payouts",
    brief:
      "Pay out thousands of sellers nightly through the provider; partial failures must be resumable without paying anyone twice.",
    budget: 16,
    checks: [
      node(["client"], "Sellers check payout status", 5),
      edge(["client"], ["gateway", "lb"], "The status API sits behind a managed edge", 10),
      node(["service"], "A payout service exposes state", 5),
      node(["queue"], "The payout run is a queue of idempotent jobs", 15),
      biEdge(["queue"], ["worker"], "Workers process payouts at a controlled rate", 10),
      edge(["worker"], ["psp"], "Workers call the payment provider", 20),
      edge(["psp"], ["queue", "worker", "service"], "Provider confirmations come back async", 10),
      edge(["worker"], ["sql"], "Run state is durable and resumable", 15),
      node(["monitor"], "A stalled run pages someone", 10),
    ],
  },
  {
    id: "kyc",
    category: "Fintech",
    name: "KYC onboarding",
    brief:
      "New users upload identity documents; verification takes minutes and involves third parties. Keep signup responsive and the audit trail complete.",
    budget: 14,
    checks: [
      node(["client"], "An applicant uploads documents", 5),
      edge(["client"], ["gateway", "lb"], "Uploads enter through a managed edge", 10),
      node(["auth"], "The applicant session is authenticated", 10),
      edge(["gateway", "lb", "auth"], ["service"], "An onboarding service accepts submissions", 10),
      edge(["service"], ["sql", "nosql"], "The application record is created immediately", 10),
      edge(["service"], ["queue"], "Verification runs async, off the signup path", 15),
      node(["queue"], "A queue holds pending verifications", 10),
      biEdge(["queue"], ["worker"], "Verification workers consume the queue", 10),
      edge(["worker"], ["sql", "nosql"], "Results and audit trail are persisted", 10),
      node(["monitor"], "Verification latency is tracked", 10),
    ],
  },
  {
    id: "fx-rates",
    category: "Fintech",
    name: "FX rate service",
    brief:
      "Every pricing call needs a fresh exchange rate. The upstream feed allows one request per second — your traffic is thousands.",
    budget: 10,
    checks: [
      node(["client"], "Pricing calls ask for rates", 5),
      edge(["client"], ["gateway", "lb"], "Traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "A rate service answers lookups", 10),
      node(["cache"], "Rates are served from cache with a TTL", 25),
      edge(["service"], ["cache"], "The hot path reads only the cache", 15),
      node(["worker"], "A single fetcher refreshes rates upstream", 10),
      edge(["worker"], ["cache"], "The fetcher writes fresh rates to the cache", 10),
      edge(["worker"], ["sql", "nosql"], "Rate history is archived", 5),
      node(["monitor"], "Staleness beyond the TTL alerts", 10),
    ],
  },
  {
    id: "invoicing",
    category: "Fintech",
    name: "Invoice generation",
    brief:
      "Month-end generates hundreds of thousands of PDFs. Users request them anytime; generation must not crowd out the interactive API.",
    budget: 13,
    checks: [
      node(["client"], "Users download invoices", 5),
      edge(["client"], ["gateway", "lb"], "The API sits behind a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An invoicing service owns requests", 10),
      edge(["service"], ["queue"], "Generation jobs are enqueued", 15),
      node(["queue"], "A queue isolates batch from interactive work", 5),
      biEdge(["queue"], ["worker"], "Render workers consume the queue", 10),
      edge(["worker"], ["nosql", "sql"], "Documents and metadata are stored", 15),
      node(["cdn"], "Heavy files are delivered via CDN", 10),
      edge(["client"], ["cdn"], "Downloads come off the edge", 10),
      node(["monitor"], "Month-end backlog is observable", 10),
    ],
  },
  {
    id: "wallet-topup",
    category: "Fintech",
    name: "Wallet top-up",
    brief:
      "Users add funds with a card; the provider confirms asynchronously. The balance must reflect exactly one credit per confirmed charge.",
    budget: 17,
    checks: [
      node(["client"], "A user tops up the wallet", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      node(["auth"], "Top-ups are authenticated", 10),
      edge(["gateway", "lb", "auth"], ["service"], "A wallet service owns the flow", 10),
      edge(["service"], ["psp"], "The service initiates the charge", 15),
      edge(["psp"], ["service", "queue", "worker"], "Confirmation arrives via webhook", 15),
      node(["queue"], "Confirmations are buffered for ordered crediting", 10),
      edge(["service", "worker"], ["sql"], "Credits are idempotent in a transactional store", 15),
      node(["monitor"], "Stuck top-ups are visible", 10),
    ],
  },
  {
    id: "chargebacks",
    category: "Fintech",
    name: "Chargeback handling",
    brief:
      "Disputes arrive as provider webhooks weeks after the charge; each opens a case, freezes funds, and must never be lost.",
    budget: 15,
    checks: [
      node(["client"], "Agents work dispute cases", 5),
      edge(["client"], ["gateway", "lb"], "The case UI sits behind a managed edge", 10),
      node(["service"], "A dispute service owns case state", 5),
      node(["psp"], "The provider is the source of disputes", 10),
      edge(["psp"], ["gateway", "service", "queue"], "Dispute webhooks are ingested", 15),
      node(["queue"], "Webhooks are buffered durably", 15),
      biEdge(["queue"], ["worker"], "Workers open and update cases", 10),
      edge(["worker"], ["sql"], "Case state and fund freezes are transactional", 15),
      node(["monitor"], "Dispute SLAs alert before deadlines", 15),
    ],
  },
  {
    id: "spend-insights",
    category: "Fintech",
    name: "Spending insights",
    brief:
      "Monthly spending breakdowns computed from millions of transactions — offline aggregation, instant reads.",
    budget: 13,
    checks: [
      node(["client"], "Users open their insights tab", 5),
      edge(["client"], ["gateway", "lb"], "Traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "An insights service serves reads", 10),
      node(["queue"], "Transaction events stream into the pipeline", 10),
      node(["worker"], "Aggregation runs offline", 15),
      edge(["worker"], ["nosql", "sql"], "Aggregates are stored for lookup", 10),
      node(["cache"], "Current-month numbers are cached", 10),
      edge(["service"], ["cache"], "Reads hit the cache first", 10),
      edge(["service"], ["nosql", "sql"], "Misses fall back to the store", 10),
      node(["monitor"], "Pipeline lag is measured", 10),
    ],
  },
];

const SOCIAL = [
  {
    id: "feed",
    category: "Social",
    name: "Social feed fan-out",
    brief:
      "A post from someone with 2M followers must land in followers' feeds within seconds — without 2M synchronous writes at post time.",
    budget: 15,
    checks: [
      node(["client"], "Clients post and scroll", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A feed service owns posts and reads", 10),
      node(["queue"], "Fan-out work is enqueued at post time", 15),
      edge(["service"], ["queue"], "Posting enqueues, it doesn't fan out inline", 10),
      biEdge(["queue"], ["worker"], "Fan-out workers materialize follower feeds", 10),
      edge(["worker"], ["nosql", "sql"], "Materialized feeds are stored", 10),
      node(["cache"], "Hot feeds are cached", 10),
      edge(["service"], ["cache"], "Scrolling reads the cache", 10),
      node(["monitor"], "Fan-out lag is measured", 10),
    ],
    warnings: [
      {
        when: ({ hasNode }) => !hasNode(["queue"]),
        text: "Fan-out happens synchronously at post time — a celebrity post becomes a 2M-write transaction.",
      },
    ],
  },
  {
    id: "follower-graph",
    category: "Social",
    name: "Follower graph reads",
    brief:
      "\"Who follows whom\" is read on every profile and feed render. Reads outnumber writes 1000:1.",
    budget: 11,
    checks: [
      node(["client"], "Every render asks the graph", 5),
      edge(["client"], ["gateway", "lb"], "Traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "A graph service answers lookups", 10),
      node(["cache"], "Adjacency reads come from memory", 20),
      edge(["service"], ["cache"], "The hot path reads the cache", 15),
      edge(["service"], ["nosql", "sql"], "The graph truth lives in a database", 15),
      node(["worker"], "Follower counts are denormalized async", 5),
      edge(["worker"], ["nosql", "sql"], "Workers maintain the denormalized counts", 10),
      node(["monitor"], "Cache hit rate is tracked", 10),
    ],
  },
  {
    id: "notifications",
    category: "Social",
    name: "Notification delivery",
    brief:
      "Likes, follows, and mentions become pushes and badge counts. Bursty and fire-and-forget — but users notice missing ones.",
    budget: 13,
    checks: [
      node(["client"], "Clients receive notifications", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A notification service accepts events", 10),
      edge(["service"], ["queue"], "Events are enqueued for delivery", 15),
      node(["queue"], "The queue absorbs engagement bursts", 10),
      biEdge(["queue"], ["worker"], "Delivery workers consume events", 10),
      edge(["worker"], ["nosql", "sql"], "The notification inbox is persisted", 10),
      node(["cache"], "Badge counts live in a fast store", 10),
      edge(["worker"], ["cache"], "Workers update badge counts", 10),
      node(["monitor"], "Delivery lag is observable", 10),
    ],
  },
  {
    id: "profile-pages",
    category: "Social",
    name: "Public profile pages",
    brief:
      "Public profiles get scraped, embedded, and hot-linked. Avatars and bios should be globally fast and cheap.",
    budget: 10,
    checks: [
      node(["client"], "Anyone loads a profile", 5),
      node(["cdn"], "Avatars and static assets sit on a CDN", 15),
      edge(["client"], ["cdn"], "Clients pull assets from the edge", 10),
      edge(["client", "cdn"], ["lb", "gateway"], "API traffic is load-balanced", 10),
      edge(["lb", "gateway"], ["service"], "A profile service serves data", 10),
      node(["cache"], "Hot profiles are cached", 15),
      edge(["service"], ["cache"], "Reads hit the cache first", 10),
      edge(["service"], ["sql", "nosql"], "Profile truth lives in a database", 15),
      node(["monitor"], "Origin offload is measured", 10),
    ],
  },
  {
    id: "trending",
    category: "Social",
    name: "Trending topics",
    brief:
      "Compute what's trending from a firehose of events; the answer updates every minute and is read from everywhere.",
    budget: 13,
    checks: [
      node(["client"], "Clients read the trending list", 5),
      edge(["client"], ["gateway", "lb"], "Traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "A trends service serves the list", 10),
      node(["queue"], "The event firehose is buffered", 15),
      biEdge(["queue"], ["worker"], "Counting workers consume the stream", 10),
      edge(["worker"], ["cache"], "Rankings are computed into a fast store", 15),
      node(["cache"], "The trending list lives in memory", 10),
      edge(["service"], ["cache"], "Reads come from the cache", 10),
      edge(["worker"], ["nosql", "sql"], "History is archived for analysis", 10),
      node(["monitor"], "Pipeline lag is visible", 5),
    ],
  },
  {
    id: "comments",
    category: "Social",
    name: "Comment threads",
    brief:
      "Deep threads under viral posts: heavy reads, moderate writes, and pagination that can't melt the database.",
    budget: 12,
    checks: [
      node(["client"], "Clients read and write comments", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A comment service owns threads", 10),
      edge(["service"], ["sql", "nosql"], "Threads are persisted durably", 15),
      node(["cache"], "Hot threads are cached page-by-page", 15),
      edge(["service"], ["cache"], "Reads hit the cache first", 15),
      node(["queue"], "Count updates are applied async", 10),
      biEdge(["queue"], ["worker"], "Workers maintain counters", 10),
      node(["monitor"], "Viral thread latency is watched", 10),
    ],
  },
  {
    id: "reactions",
    category: "Social",
    name: "Reaction counters",
    brief:
      "Millions of likes per minute on hot content. Counts can lag a few seconds but must not lose increments.",
    budget: 12,
    checks: [
      node(["client"], "Clients tap reactions", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A reaction service absorbs taps", 10),
      node(["cache"], "Counters increment in memory", 20),
      edge(["service"], ["cache"], "The write path is the cache, not the DB", 15),
      node(["queue"], "Increments stream out for durable flush", 10),
      biEdge(["queue"], ["worker"], "Flush workers drain the stream", 10),
      edge(["worker"], ["sql", "nosql"], "Counts are reconciled durably", 10),
      node(["monitor"], "Drift between cache and store is measured", 10),
    ],
  },
  {
    id: "moderation",
    category: "Social",
    name: "UGC moderation pipeline",
    brief:
      "Everything uploaded passes automated screening; flagged items wait for human review. Publishing is async but feels instant.",
    budget: 14,
    checks: [
      node(["client"], "Users upload content", 5),
      edge(["client"], ["gateway", "lb"], "Uploads enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An intake service accepts uploads", 10),
      edge(["service"], ["queue"], "Screening jobs are enqueued", 15),
      node(["queue"], "The queue holds the moderation backlog", 10),
      biEdge(["queue"], ["worker"], "Screening workers consume the queue", 15),
      edge(["worker"], ["nosql", "sql"], "Verdicts are persisted", 10),
      edge(["service"], ["nosql", "sql"], "Content state is readable immediately", 10),
      node(["monitor"], "Review backlog size alerts", 15),
    ],
  },
  {
    id: "media-tagging",
    category: "Social",
    name: "Photo tagging pipeline",
    brief:
      "Uploaded photos get faces and objects tagged by ML within a minute — entirely off the upload path.",
    budget: 14,
    checks: [
      node(["client"], "Users upload photos", 5),
      edge(["client"], ["gateway", "lb"], "Uploads enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An upload service accepts photos", 10),
      edge(["service"], ["queue"], "Tagging jobs are enqueued", 15),
      node(["queue"], "The queue feeds the ML farm", 10),
      biEdge(["queue"], ["worker"], "Tagging workers consume jobs", 10),
      edge(["worker"], ["nosql", "sql"], "Tags are persisted for search", 15),
      node(["cdn"], "Originals are delivered from the edge", 10),
      edge(["client"], ["cdn"], "Clients fetch images from the CDN", 10),
      node(["monitor"], "Tagging latency is tracked", 5),
    ],
  },
  {
    id: "people-search",
    category: "Social",
    name: "People search",
    brief:
      "Find-a-user by name with typo tolerance; the index lags profile edits by seconds at most.",
    budget: 11,
    checks: [
      node(["client"], "Clients search for people", 5),
      edge(["client"], ["gateway", "lb"], "Traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "A search service answers queries", 10),
      edge(["service"], ["nosql", "sql"], "Queries hit a search index store", 15),
      node(["cache"], "Frequent queries are cached", 10),
      edge(["service"], ["cache"], "The cache absorbs repeats", 10),
      node(["queue"], "Profile edits stream to the indexer", 10),
      node(["worker"], "An index updater applies changes", 10),
      edge(["worker"], ["nosql", "sql"], "The index is updated incrementally", 10),
      node(["monitor"], "Index freshness is measured", 10),
    ],
  },
];

const REALTIME = [
  {
    id: "chat",
    category: "Realtime",
    name: "Realtime chat delivery",
    brief:
      "1-on-1 and group messages with per-conversation ordering, offline catch-up, and delivery receipts.",
    budget: 15,
    checks: [
      node(["client"], "Clients hold open connections", 5),
      edge(["client"], ["gateway"], "Persistent connections terminate at an edge gateway", 15),
      edge(["gateway"], ["service"], "A chat service routes messages", 10),
      node(["queue"], "Per-conversation ordering goes through a queue", 15),
      edge(["service"], ["queue"], "Sends are enqueued", 10),
      biEdge(["queue"], ["worker"], "Delivery workers fan messages out", 10),
      edge(["worker"], ["nosql", "sql"], "History is persisted for catch-up", 10),
      node(["cache"], "Presence and undelivered counts live in memory", 10),
      edge(["service"], ["cache"], "The service reads session state from cache", 10),
      node(["monitor"], "Delivery latency is watched", 5),
    ],
    warnings: [
      {
        when: ({ hasNode }) => !hasNode(["queue"]),
        text: "No queue between send and delivery — reconnect storms and group bursts will drop or reorder messages.",
      },
    ],
  },
  {
    id: "presence",
    category: "Realtime",
    name: "Presence service",
    brief:
      "Online/offline dots for millions of users via heartbeats. State is ephemeral — losing it costs seconds of accuracy, not data.",
    budget: 10,
    checks: [
      node(["client"], "Clients send heartbeats", 5),
      edge(["client"], ["gateway", "lb"], "Heartbeats terminate at the edge", 15),
      edge(["gateway", "lb"], ["service"], "A presence service ingests beats", 10),
      node(["cache"], "Presence lives in memory with TTLs — nowhere else", 25),
      edge(["service"], ["cache"], "Reads and writes go to the cache", 15),
      node(["worker"], "A sweeper expires stale entries", 10),
      edge(["worker"], ["cache"], "The sweeper works against the cache", 10),
      node(["monitor"], "Heartbeat throughput is visible", 10),
    ],
    warnings: [
      {
        when: ({ hasEdge }) => hasEdge(["service", "worker"], ["sql", "nosql"]),
        text: "Persisting every heartbeat — presence is ephemeral by design; the database adds cost and latency for nothing.",
      },
    ],
  },
  {
    id: "live-auction",
    category: "Realtime",
    name: "Live auction bids",
    brief:
      "Bids on a hot lot arrive in bursts; the current high bid must be authoritative and the audit trail complete.",
    budget: 14,
    checks: [
      node(["client"], "Bidders watch and bid live", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An auction service accepts bids", 10),
      node(["queue"], "Bids are strictly ordered through a queue", 15),
      edge(["service"], ["queue"], "Bids are enqueued, not raced", 10),
      biEdge(["queue"], ["worker"], "A single consumer applies bids in order", 10),
      edge(["worker"], ["sql"], "The audit trail is transactional", 15),
      node(["cache"], "The current high bid is readable instantly", 10),
      edge(["worker"], ["cache"], "The consumer publishes the new high bid", 10),
      node(["monitor"], "Bid latency is watched during the close", 5),
    ],
  },
  {
    id: "live-scores",
    category: "Realtime",
    name: "Live sports scores",
    brief:
      "One score update fans out to millions of viewers within a second. Every read is identical — cache everything.",
    budget: 11,
    checks: [
      node(["client"], "Millions of clients poll or subscribe", 5),
      edge(["client"], ["cdn", "gateway", "lb"], "Traffic is absorbed at the edge", 10),
      edge(["cdn", "gateway", "lb"], ["service"], "A score service answers", 10),
      node(["cache"], "The current score lives in memory", 20),
      edge(["service"], ["cache"], "All reads come from the cache", 15),
      node(["worker"], "A feed consumer ingests the official feed", 10),
      edge(["worker"], ["cache"], "The consumer updates the score", 10),
      edge(["worker"], ["sql", "nosql"], "Match history is archived", 10),
      node(["monitor"], "Update-to-visible latency is measured", 10),
    ],
  },
  {
    id: "collab-docs",
    category: "Realtime",
    name: "Collaborative editing",
    brief:
      "Multiple cursors in one document: every keystroke is an operation that must apply in the same order for everyone.",
    budget: 13,
    checks: [
      node(["client"], "Editors hold live connections", 5),
      edge(["client"], ["gateway"], "Connections terminate at an edge gateway", 15),
      edge(["gateway"], ["service"], "A doc service routes operations", 10),
      node(["queue"], "Operations are ordered per document", 15),
      edge(["service"], ["queue"], "Edits are enqueued", 10),
      biEdge(["queue"], ["worker"], "An applier consumes operations in order", 10),
      edge(["worker"], ["nosql", "sql"], "Snapshots are persisted", 10),
      node(["cache"], "Live document state is held in memory", 10),
      edge(["service"], ["cache"], "Joins read the live state fast", 10),
      node(["monitor"], "Apply lag is watched", 5),
    ],
  },
  {
    id: "push-gateway",
    category: "Realtime",
    name: "Mobile push pipeline",
    brief:
      "Server events become APNs/FCM pushes. Provider rate limits and retries are your problem, not the callers'.",
    budget: 12,
    checks: [
      node(["client"], "Devices receive pushes", 5),
      edge(["client"], ["gateway", "lb"], "Registration traffic enters at the edge", 10),
      edge(["gateway", "lb"], ["service"], "A push service accepts send requests", 10),
      edge(["service"], ["queue"], "Sends are enqueued immediately", 15),
      node(["queue"], "The queue decouples callers from providers", 5),
      biEdge(["queue"], ["worker"], "Sender workers drain the queue", 10),
      node(["worker"], "Workers own provider integration, throttling, and retries", 10),
      edge(["worker"], ["nosql", "sql"], "Delivery state and tokens are persisted", 10),
      node(["monitor"], "Provider error rates alert", 15),
      node(["cache"], "Device token lookups are cached", 10),
    ],
  },
  {
    id: "support-chat",
    category: "Realtime",
    name: "Support live chat",
    brief:
      "Customers queue for the next free agent; transcripts persist; abandonment is watched closely.",
    budget: 13,
    checks: [
      node(["client"], "Customers and agents connect", 5),
      edge(["client"], ["gateway"], "Connections terminate at an edge gateway", 10),
      edge(["gateway"], ["service"], "A routing service owns conversations", 10),
      node(["queue"], "Waiting customers form a fair queue", 15),
      edge(["service"], ["queue"], "New chats are enqueued", 10),
      biEdge(["queue"], ["worker"], "Assignment workers match agents", 10),
      edge(["service"], ["sql"], "Transcripts are persisted", 10),
      node(["cache"], "Agent availability lives in memory", 10),
      edge(["service"], ["cache"], "Routing reads availability fast", 10),
      node(["monitor"], "Wait time and abandonment alert", 10),
    ],
  },
  {
    id: "stock-ticker",
    category: "Realtime",
    name: "Market data ticker",
    brief:
      "Exchange feed in, last-price out to every open dashboard. Milliseconds matter; the database is not on this path.",
    budget: 11,
    checks: [
      node(["client"], "Dashboards subscribe to prices", 5),
      edge(["client"], ["gateway"], "Subscriptions terminate at an edge gateway", 15),
      edge(["gateway"], ["service"], "A ticker service serves the feed", 10),
      node(["worker"], "A feed consumer ingests exchange data", 10),
      edge(["worker"], ["cache"], "Last prices are written to memory", 15),
      node(["cache"], "The hot path is memory only", 15),
      edge(["service"], ["cache"], "Reads come from the cache", 15),
      edge(["worker"], ["nosql", "sql"], "End-of-day data is archived", 5),
      node(["monitor"], "Tick-to-client latency is measured", 10),
    ],
    warnings: [
      {
        when: ({ hasEdge }) => hasEdge(["service"], ["sql", "nosql"]),
        text: "The database sits on the hot read path — last-price reads belong in memory.",
      },
    ],
  },
  {
    id: "multiplayer-lobby",
    category: "Realtime",
    name: "Multiplayer lobby",
    brief:
      "Players gather, ready-up, and launch together; lobby state changes broadcast instantly and vanish when the match starts.",
    budget: 12,
    checks: [
      node(["client"], "Players join lobbies", 5),
      edge(["client"], ["gateway"], "Connections terminate at an edge gateway", 15),
      edge(["gateway"], ["service"], "A lobby service owns state changes", 10),
      node(["cache"], "Lobby state is ephemeral, held in memory", 20),
      edge(["service"], ["cache"], "State reads and writes hit the cache", 15),
      node(["queue"], "Match-start events flow downstream", 10),
      biEdge(["queue"], ["worker"], "Workers spin up matches", 10),
      edge(["worker"], ["sql", "nosql"], "Match records are persisted", 10),
      node(["monitor"], "Lobby churn is observable", 5),
    ],
  },
  {
    id: "courier-stream",
    category: "Realtime",
    name: "Courier location stream",
    brief:
      "Courier apps ping GPS every 3 seconds; customers watch the dot move. Ingest must absorb rush hour.",
    budget: 12,
    checks: [
      node(["client"], "Couriers ping, customers watch", 5),
      edge(["client"], ["gateway", "lb"], "Pings enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An ingest service validates pings", 10),
      node(["queue"], "Pings are buffered against rush hour", 15),
      edge(["service"], ["queue"], "Ingest enqueues, it doesn't write inline", 10),
      biEdge(["queue"], ["worker"], "Workers process the stream", 10),
      edge(["worker"], ["cache"], "Latest positions land in memory", 15),
      node(["cache"], "The map read path is the cache", 10),
      edge(["service"], ["cache"], "Customer reads come from the cache", 10),
      node(["monitor"], "Ping lag is measured", 5),
    ],
  },
];

const CONTENT = [
  {
    id: "media-upload",
    category: "Content & Media",
    name: "Media upload & transcode",
    brief:
      "Uploads return immediately; transcoding to multiple resolutions happens in the background; playback comes off the CDN.",
    budget: 15,
    checks: [
      node(["client"], "Creators upload, viewers play", 5),
      edge(["client"], ["gateway", "lb"], "Uploads enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An upload service accepts files", 10),
      edge(["service"], ["queue"], "Transcode jobs are enqueued", 15),
      biEdge(["queue"], ["worker"], "The transcode farm consumes jobs", 10),
      node(["worker"], "Workers do the heavy encoding", 10),
      edge(["worker"], ["nosql", "sql"], "Rendition metadata is persisted", 10),
      node(["cdn"], "Playback is delivered from the edge", 15),
      edge(["client"], ["cdn"], "Viewers stream from the CDN", 10),
      node(["monitor"], "Transcode backlog is observable", 5),
    ],
    warnings: [
      {
        when: ({ hasNode }) => !hasNode(["cdn"]),
        text: "Serving video straight from origin — bandwidth costs and latency will bury you without a CDN.",
      },
    ],
  },
  {
    id: "video-playback",
    category: "Content & Media",
    name: "Premium video playback",
    brief:
      "Premium video: segments must be cheap to serve worldwide but playable only by entitled viewers.",
    budget: 11,
    checks: [
      node(["client"], "Viewers stream video", 5),
      node(["cdn"], "Segments live on a CDN", 20),
      edge(["client"], ["cdn"], "Playback pulls from the edge", 15),
      edge(["client"], ["gateway", "lb"], "Entitlement checks enter via API", 10),
      node(["auth"], "Entitlement is enforced before tokens are issued", 15),
      edge(["gateway", "lb", "auth"], ["service"], "A playback service issues signed URLs", 10),
      edge(["service"], ["sql", "nosql"], "Entitlements live in a database", 10),
      node(["cache"], "Token and entitlement lookups are cached", 5),
      node(["monitor"], "Playback failures are observable", 10),
    ],
  },
  {
    id: "image-resize",
    category: "Content & Media",
    name: "Image resizing service",
    brief:
      "Every device wants a different size. Resize once, cache forever, serve from the edge.",
    budget: 12,
    checks: [
      node(["client"], "Clients request sized images", 5),
      node(["cdn"], "Variants are served from the edge", 15),
      edge(["client"], ["cdn"], "Requests hit the CDN first", 15),
      edge(["cdn"], ["lb", "gateway"], "Misses fall through to origin", 10),
      edge(["lb", "gateway"], ["service"], "A resize service renders on miss", 10),
      node(["cache"], "Resized variants are cached at origin too", 15),
      edge(["service"], ["cache"], "The service checks the variant cache", 10),
      edge(["service"], ["nosql", "sql"], "Original metadata lives in a store", 10),
      node(["monitor"], "Resize latency and hit rate are tracked", 10),
    ],
  },
  {
    id: "podcast-feeds",
    category: "Content & Media",
    name: "Podcast feed delivery",
    brief:
      "RSS feeds polled relentlessly by apps; audio files are large and static. Origin should barely notice.",
    budget: 9,
    checks: [
      node(["client"], "Podcast apps poll feeds", 5),
      node(["cdn"], "Audio and feeds are served from the edge", 20),
      edge(["client"], ["cdn"], "Polling hits the CDN", 20),
      edge(["cdn"], ["lb", "gateway"], "Misses go to origin", 10),
      edge(["lb", "gateway"], ["service"], "A feed service renders RSS", 10),
      node(["cache"], "Rendered feeds are cached", 15),
      edge(["service"], ["cache"], "The service serves from cache", 10),
      edge(["service"], ["sql", "nosql"], "Episode metadata lives in a database", 10),
    ],
  },
  {
    id: "live-ingest",
    category: "Content & Media",
    name: "Live stream ingest",
    brief:
      "Streamers push live video; viewers watch with a few seconds' delay. Segment, store, distribute — continuously.",
    budget: 14,
    checks: [
      node(["client"], "Streamers push, viewers watch", 5),
      edge(["client"], ["gateway"], "Ingest terminates at an edge gateway", 10),
      edge(["gateway"], ["service"], "An ingest service accepts streams", 10),
      edge(["service"], ["queue"], "Segmenting jobs flow through a queue", 10),
      biEdge(["queue"], ["worker"], "Segmenters consume continuously", 10),
      edge(["worker"], ["nosql", "sql"], "Segments and manifests are stored", 10),
      node(["cdn"], "Viewers pull segments from the edge", 15),
      edge(["worker", "service"], ["cdn"], "Origin feeds the CDN", 10),
      edge(["client"], ["cdn"], "Playback comes off the CDN", 10),
      node(["monitor"], "Glass-to-glass latency is measured", 10),
    ],
  },
  {
    id: "blog-platform",
    category: "Content & Media",
    name: "Multi-author blog",
    brief:
      "Classic read-heavy publishing: a post goes viral, the site stays up, the bill stays flat.",
    budget: 9,
    checks: [
      node(["client"], "Readers load posts", 5),
      node(["cdn"], "Static assets ship from the edge", 15),
      edge(["client"], ["cdn"], "Assets come off the CDN", 10),
      edge(["client", "cdn"], ["lb", "gateway"], "Page traffic is load-balanced", 10),
      edge(["lb", "gateway"], ["service"], "A rendering service serves pages", 10),
      node(["cache"], "Rendered pages are cached", 15),
      edge(["service"], ["cache"], "Reads hit the cache first", 10),
      edge(["service"], ["sql", "nosql"], "Content truth lives in a database", 15),
      node(["monitor"], "Origin load is observable", 10),
    ],
  },
  {
    id: "news-home",
    category: "Content & Media",
    name: "Breaking-news homepage",
    brief:
      "Editors update constantly during breaking news while traffic spikes 20×. Freshness within seconds, served mostly from cache.",
    budget: 11,
    checks: [
      node(["client"], "Readers hammer the homepage", 5),
      node(["cdn"], "The edge absorbs most reads", 10),
      edge(["client"], ["cdn"], "Readers hit the CDN", 10),
      edge(["client", "cdn"], ["lb", "gateway"], "Dynamic traffic is load-balanced", 10),
      edge(["lb", "gateway"], ["service"], "A page service renders the homepage", 10),
      node(["cache"], "The rendered page is cached with short TTLs", 20),
      edge(["service"], ["cache"], "Reads come from cache", 10),
      node(["queue"], "Edit events drive invalidation", 5),
      node(["worker"], "An invalidator refreshes caches on publish", 5),
      edge(["service"], ["sql", "nosql"], "Content truth lives in a database", 10),
      node(["monitor"], "Staleness during spikes is measured", 5),
    ],
  },
  {
    id: "ugc-gallery",
    category: "Content & Media",
    name: "UGC photo gallery",
    brief:
      "Public uploads with screening before visibility, thumbnails for every device, delivery from the edge.",
    budget: 14,
    checks: [
      node(["client"], "Users upload and browse", 5),
      edge(["client"], ["gateway", "lb"], "Uploads enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An intake service accepts uploads", 10),
      edge(["service"], ["queue"], "Screening and thumbnailing are enqueued", 10),
      node(["queue"], "The pipeline absorbs upload bursts", 10),
      biEdge(["queue"], ["worker"], "Workers screen and resize", 10),
      edge(["worker"], ["nosql", "sql"], "Approved media metadata is stored", 10),
      node(["cdn"], "Browsing is served from the edge", 15),
      edge(["client"], ["cdn"], "Clients pull images from the CDN", 10),
      node(["monitor"], "Screening backlog alerts", 10),
    ],
  },
  {
    id: "subtitles",
    category: "Content & Media",
    name: "Subtitle generation",
    brief:
      "Speech-to-text for every uploaded video, in 30+ languages, hours of audio per minute of wall clock.",
    budget: 13,
    checks: [
      node(["client"], "Creators upload videos", 5),
      edge(["client"], ["gateway", "lb"], "Uploads enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An intake service accepts jobs", 10),
      edge(["service"], ["queue"], "Transcription jobs are enqueued", 15),
      node(["queue"], "The queue feeds the transcription farm", 10),
      biEdge(["queue"], ["worker"], "Transcription workers consume jobs", 10),
      node(["worker"], "Workers scale with the backlog", 10),
      edge(["worker"], ["nosql", "sql"], "Transcripts are stored per language", 15),
      node(["monitor"], "Backlog and per-language failures alert", 15),
    ],
  },
  {
    id: "downloads",
    category: "Content & Media",
    name: "Software download center",
    brief:
      "Multi-GB installers, release-day spikes, and signed URLs so leeches can't hotlink.",
    budget: 10,
    checks: [
      node(["client"], "Users download releases", 5),
      node(["cdn"], "Binaries ship from the edge", 20),
      edge(["client"], ["cdn"], "Downloads come off the CDN", 15),
      edge(["client"], ["gateway", "lb"], "The API issues signed URLs", 10),
      node(["auth"], "Signed access is enforced", 10),
      edge(["gateway", "lb", "auth"], ["service"], "A release service owns metadata", 10),
      edge(["service"], ["sql", "nosql"], "Release metadata lives in a database", 10),
      node(["cache"], "Hot metadata is cached", 10),
      node(["monitor"], "Release-day bandwidth is watched", 10),
    ],
  },
];

const DATA = [
  {
    id: "clickstream",
    category: "Data & Analytics",
    name: "Clickstream ingestion",
    brief:
      "Every page view and tap from every user, ingested without back-pressure on the apps emitting them.",
    budget: 13,
    checks: [
      node(["client"], "Apps emit events", 5),
      edge(["client"], ["gateway", "lb"], "Events enter through a managed edge", 15),
      edge(["gateway", "lb"], ["service"], "A collector validates and batches", 10),
      edge(["service"], ["queue"], "Events are enqueued immediately", 20),
      node(["queue"], "The queue absorbs any spike", 10),
      biEdge(["queue"], ["worker"], "Consumers drain at their own pace", 10),
      edge(["worker"], ["nosql", "sql"], "Events land in an analytical store", 15),
      node(["monitor"], "Ingest lag and drop rate are visible", 15),
    ],
  },
  {
    id: "ab-testing",
    category: "Data & Analytics",
    name: "Experiment assignment",
    brief:
      "Which variant does this user see? Answered on every request in microseconds, consistent per user for weeks.",
    budget: 10,
    checks: [
      node(["client"], "Every request asks for its variant", 5),
      edge(["client"], ["gateway", "lb"], "Traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "An assignment service answers", 10),
      node(["cache"], "Assignments and configs are served from memory", 25),
      edge(["service"], ["cache"], "The hot path is cache-only", 15),
      edge(["service"], ["sql", "nosql"], "Experiment config truth lives in a database", 10),
      node(["worker"], "Config changes propagate asynchronously", 5),
      edge(["worker"], ["cache"], "The propagator refreshes the cache", 10),
      node(["monitor"], "Assignment latency is tracked", 10),
    ],
  },
  {
    id: "metrics-dash",
    category: "Data & Analytics",
    name: "Metrics dashboard",
    brief:
      "Engineers stare at dashboards all day; queries aggregate millions of points but the same charts repeat.",
    budget: 11,
    checks: [
      node(["client"], "Engineers load dashboards", 5),
      edge(["client"], ["gateway", "lb"], "Traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "A query service serves charts", 10),
      node(["cache"], "Repeated chart queries are cached", 15),
      edge(["service"], ["cache"], "Reads hit the cache first", 15),
      edge(["service"], ["nosql", "sql"], "The metrics store answers misses", 15),
      node(["worker"], "Rollups are precomputed", 10),
      edge(["worker"], ["nosql", "sql"], "Workers write rollup tables", 10),
      node(["monitor"], "Query latency is itself monitored", 10),
    ],
  },
  {
    id: "log-pipeline",
    category: "Data & Analytics",
    name: "Log aggregation",
    brief:
      "Every service ships structured logs; engineers search them seconds later. Ingest spikes exactly when something breaks — when you need it most.",
    budget: 13,
    checks: [
      node(["client"], "Services ship logs", 5),
      edge(["client"], ["gateway", "lb"], "Log traffic enters through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An ingest tier validates and batches", 10),
      edge(["service"], ["queue"], "Logs are enqueued, never dropped", 15),
      node(["queue"], "The queue rides out incident spikes", 10),
      biEdge(["queue"], ["worker"], "Indexer workers consume the stream", 10),
      edge(["worker"], ["nosql", "sql"], "Logs land in a search index", 15),
      edge(["service"], ["nosql", "sql"], "The search API queries the index", 10),
      node(["monitor"], "Ingest lag alerts — meta but critical", 15),
    ],
  },
  {
    id: "recs-precompute",
    category: "Data & Analytics",
    name: "Recommendation pipeline",
    brief:
      "Models retrain nightly; serving must be a dumb, fast lookup.",
    budget: 12,
    checks: [
      node(["client"], "Apps request recommendations", 5),
      edge(["client"], ["gateway", "lb"], "Traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "A serving layer does lookups only", 10),
      node(["queue"], "Behavior events stream into training", 10),
      node(["worker"], "Batch training runs offline", 15),
      edge(["worker"], ["nosql", "sql"], "Model output lands in a serving store", 15),
      node(["cache"], "Hot users' lists are cached", 10),
      edge(["service"], ["cache"], "Serving reads the cache first", 10),
      edge(["service"], ["nosql", "sql"], "Misses fall back to the store", 10),
      node(["monitor"], "Staleness of servings is tracked", 5),
    ],
  },
  {
    id: "search-indexing",
    category: "Data & Analytics",
    name: "Search index pipeline",
    brief:
      "Catalog edits appear in search within seconds. Reindexing the world happens without downtime.",
    budget: 13,
    checks: [
      node(["client"], "Users search the catalog", 5),
      edge(["client"], ["gateway", "lb"], "Search traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "A search API serves queries", 10),
      edge(["service"], ["nosql", "sql"], "Queries hit the index store", 10),
      node(["queue"], "A change feed streams edits", 15),
      biEdge(["queue"], ["worker"], "Indexers consume the feed", 10),
      edge(["worker"], ["nosql", "sql"], "The index updates incrementally", 15),
      node(["cache"], "Hot queries are cached", 10),
      node(["monitor"], "Index freshness is measured", 15),
    ],
  },
  {
    id: "gdpr-wipe",
    category: "Data & Analytics",
    name: "GDPR deletion pipeline",
    brief:
      "A deletion request must reach every store within 30 days, with proof. Partial completion is a lawsuit.",
    budget: 13,
    checks: [
      node(["client"], "Users request deletion", 5),
      edge(["client"], ["gateway", "lb"], "Requests enter through a managed edge", 10),
      node(["auth"], "Identity is verified before erasure", 10),
      edge(["gateway", "lb", "auth"], ["service"], "An orchestrator owns the workflow", 10),
      edge(["service"], ["queue"], "Per-store deletion tasks are enqueued", 15),
      node(["queue"], "The queue makes the workflow resumable", 10),
      biEdge(["queue"], ["worker"], "Deletion workers fan out", 10),
      edge(["worker"], ["sql"], "Relational data is erased with an audit row", 10),
      edge(["worker"], ["nosql"], "Document data is erased too", 10),
      node(["monitor"], "Deadline breaches alert loudly", 10),
    ],
  },
  {
    id: "nightly-reports",
    category: "Data & Analytics",
    name: "Nightly reporting",
    brief:
      "Heavy aggregation runs at 2am; results are ready before the first coffee. Failures page someone.",
    budget: 11,
    checks: [
      node(["queue"], "The job graph is orchestrated through a queue", 15),
      biEdge(["queue"], ["worker"], "Batch workers consume jobs", 10),
      node(["worker"], "Workers do the heavy aggregation", 15),
      edge(["worker"], ["sql", "nosql"], "Results land in a reporting store", 15),
      node(["monitor"], "A failed run pages before morning", 20),
      node(["client"], "Analysts read reports", 5),
      edge(["client"], ["gateway", "lb"], "Report traffic is load-balanced", 5),
      edge(["gateway", "lb"], ["service"], "A report service serves results", 5),
      edge(["service"], ["sql", "nosql"], "Reads come from the reporting store", 10),
    ],
  },
  {
    id: "anomaly-detect",
    category: "Data & Analytics",
    name: "Anomaly alerting",
    brief:
      "Streaming metrics watched for spikes; alert within a minute, don't cry wolf.",
    budget: 12,
    checks: [
      node(["client"], "Systems emit metrics", 5),
      edge(["client"], ["gateway", "lb"], "Metrics enter through a managed edge", 5),
      edge(["gateway", "lb"], ["service"], "An ingest tier batches metrics", 5),
      node(["queue"], "The metric stream is buffered", 15),
      biEdge(["queue"], ["worker"], "Detector workers consume the stream", 10),
      node(["worker"], "Detectors compare against baselines", 15),
      edge(["worker"], ["cache"], "Baselines are kept hot in memory", 10),
      node(["cache"], "Baseline state lives in a fast store", 10),
      edge(["worker"], ["sql", "nosql"], "Incidents are recorded", 5),
      node(["monitor"], "The alerting path is itself monitored", 20),
    ],
  },
  {
    id: "data-export",
    category: "Data & Analytics",
    name: "Self-serve data export",
    brief:
      "Users request a full export; it's gigabytes and takes minutes. Build it async, notify, and hand over an expiring link.",
    budget: 13,
    checks: [
      node(["client"], "Users request and download exports", 5),
      edge(["client"], ["gateway", "lb"], "Requests enter through a managed edge", 10),
      node(["auth"], "Exports are authenticated — it's all their data", 10),
      edge(["gateway", "lb", "auth"], ["service"], "An export service owns requests", 10),
      edge(["service"], ["queue"], "Export jobs are enqueued", 15),
      node(["queue"], "The queue isolates batch work", 10),
      biEdge(["queue"], ["worker"], "Builder workers assemble archives", 10),
      edge(["worker"], ["nosql", "sql"], "Job state and artifacts are recorded", 10),
      node(["cdn"], "Downloads are delivered from the edge", 10),
      node(["monitor"], "Stuck exports are visible", 10),
    ],
  },
];

const INFRA = [
  {
    id: "url-shortener",
    category: "Infrastructure",
    name: "URL shortener at scale",
    brief:
      "Billions of redirects, 100:1 read-to-write, p99 under 20ms. A mapping never changes once created.",
    budget: 10,
    checks: [
      node(["client"], "Clients follow short links", 5),
      edge(["client"], ["cdn", "lb", "gateway"], "Redirects are absorbed at the edge", 10),
      node(["cdn"], "Immutable mappings cache at the edge", 10),
      edge(["cdn", "lb", "gateway"], ["service"], "A redirect service answers misses", 10),
      node(["cache"], "Hot mappings live in memory", 25),
      edge(["service"], ["cache"], "The hot path reads the cache", 15),
      edge(["service"], ["nosql", "sql"], "The mapping store is the source of truth", 15),
      node(["monitor"], "Redirect p99 is watched", 10),
    ],
    warnings: [
      {
        when: ({ hasNode }) => !hasNode(["cache"]),
        text: "Every redirect hits the database — at billions of reads this is the whole problem.",
      },
    ],
  },
  {
    id: "rate-limited-api",
    category: "Infrastructure",
    name: "Rate-limited public API",
    brief:
      "A public API with per-key quotas enforced before requests ever reach your services.",
    budget: 11,
    checks: [
      node(["client"], "Third parties call the API", 5),
      node(["gateway"], "A gateway fronts everything", 20),
      edge(["client"], ["gateway"], "All traffic goes through the gateway", 10),
      node(["auth"], "Keys are validated at the edge", 10),
      node(["cache"], "Quota counters live in a fast shared store", 15),
      edge(["gateway"], ["cache"], "The gateway checks quotas in the cache", 15),
      edge(["gateway"], ["service"], "Only admitted requests reach services", 10),
      edge(["service"], ["sql", "nosql"], "Key and plan truth lives in a database", 5),
      node(["monitor"], "Throttle rates per key are observable", 10),
    ],
  },
  {
    id: "api-keys",
    category: "Infrastructure",
    name: "API key management",
    brief:
      "Issue, rotate, and validate keys. Validation happens on every request; issuance is rare.",
    budget: 11,
    checks: [
      node(["client"], "Every API call presents a key", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through the edge", 10),
      node(["gateway"], "Validation happens before routing", 10),
      node(["auth"], "An auth service owns key lifecycle", 15),
      node(["cache"], "Key lookups are served from memory", 20),
      edge(["gateway", "auth", "service"], ["cache"], "Validation reads the cache", 15),
      edge(["auth", "service"], ["sql", "nosql"], "Key truth lives in a database", 10),
      node(["monitor"], "Invalid-key spikes alert", 10),
      node(["service"], "Product services sit behind validation", 5),
    ],
  },
  {
    id: "webhook-ingest",
    category: "Infrastructure",
    name: "Webhook ingestion",
    brief:
      "Partners fire webhooks in unpredictable bursts and expect a fast 2xx. Process later, never lose one.",
    budget: 13,
    checks: [
      node(["client"], "Partners fire webhooks", 5),
      edge(["client"], ["gateway", "lb"], "Webhooks enter through a managed edge", 15),
      edge(["gateway", "lb"], ["service"], "A thin receiver validates signatures", 10),
      edge(["service"], ["queue"], "Payloads are enqueued before the 2xx", 20),
      node(["queue"], "The queue is the durability boundary", 10),
      biEdge(["queue"], ["worker"], "Processors consume at their own pace", 10),
      edge(["worker"], ["sql", "nosql"], "Processed results are persisted", 15),
      node(["monitor"], "Queue depth and processing lag alert", 15),
    ],
    warnings: [
      {
        when: ({ hasNode }) => !hasNode(["queue"]),
        text: "Webhooks processed synchronously — a partner burst times out, they retry, and the burst doubles.",
      },
    ],
  },
  {
    id: "feature-flags",
    category: "Infrastructure",
    name: "Feature flag service",
    brief:
      "Every request everywhere asks \"is this flag on?\". Reads must be near-free; changes propagate in seconds.",
    budget: 10,
    checks: [
      node(["client"], "Every surface evaluates flags", 5),
      edge(["client"], ["gateway", "lb"], "Flag traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "A flag service serves evaluations", 10),
      node(["cache"], "Flag state is served from memory", 25),
      edge(["service"], ["cache"], "The hot path is cache-only", 15),
      edge(["service"], ["sql", "nosql"], "Flag config truth lives in a database", 15),
      node(["worker"], "Changes propagate asynchronously", 5),
      edge(["worker"], ["cache"], "The propagator refreshes caches", 5),
      node(["monitor"], "Propagation delay is measured", 10),
    ],
  },
  {
    id: "sso-login",
    category: "Infrastructure",
    name: "SSO login flow",
    brief:
      "Single sign-on for every product surface; sessions verified on every request without hammering the identity provider.",
    budget: 11,
    checks: [
      node(["client"], "Users sign in once", 5),
      edge(["client"], ["gateway", "lb"], "Login traffic enters at the edge", 10),
      node(["auth"], "A dedicated auth service owns the flow", 25),
      edge(["gateway", "lb"], ["auth"], "The edge routes to auth", 10),
      node(["cache"], "Sessions are verified against a fast store", 15),
      edge(["auth"], ["cache"], "Auth reads and writes sessions in cache", 10),
      edge(["auth"], ["sql", "nosql"], "Account truth lives in a database", 10),
      node(["service"], "Product services trust verified sessions", 5),
      node(["monitor"], "Login failures and latency alert", 10),
    ],
  },
  {
    id: "session-store",
    category: "Infrastructure",
    name: "Stateless app sessions",
    brief:
      "Any instance can serve any user mid-session; deploys and instance death must not log anyone out.",
    budget: 10,
    checks: [
      node(["client"], "Users carry sessions across requests", 5),
      edge(["client"], ["lb", "gateway"], "Requests spread across instances", 15),
      edge(["lb", "gateway"], ["service"], "Stateless services serve any user", 10),
      node(["cache"], "Sessions live in a shared fast store", 25),
      edge(["service"], ["cache"], "Every request reads the session store", 20),
      edge(["service"], ["sql", "nosql"], "Durable user data stays in the database", 10),
      node(["auth"], "Session issuance is owned by auth", 5),
      node(["monitor"], "Session store health is critical-path", 10),
    ],
  },
  {
    id: "status-page",
    category: "Infrastructure",
    name: "Public status page",
    brief:
      "When production burns, everyone loads this page at once — it must not share production's fate.",
    budget: 8,
    checks: [
      node(["client"], "Everyone checks at the same time", 5),
      node(["cdn"], "The page itself is static, on a CDN", 25),
      edge(["client"], ["cdn"], "All reads come off the edge", 20),
      node(["monitor"], "Probes generate the status truth", 20),
      node(["worker"], "A publisher renders status to static files", 10),
      edge(["worker"], ["nosql", "sql"], "Incident history is stored", 10),
      node(["cache"], "API reads are cached as a fallback", 10),
    ],
  },
  {
    id: "file-transfer",
    category: "Infrastructure",
    name: "Resumable file transfer",
    brief:
      "Multi-GB uploads over flaky connections: chunked, resumable, and virus-scanned before anyone can download.",
    budget: 14,
    checks: [
      node(["client"], "Users upload and download files", 5),
      edge(["client"], ["gateway", "lb"], "Chunks enter through a managed edge", 10),
      node(["auth"], "Transfers are authenticated", 10),
      edge(["gateway", "lb", "auth"], ["service"], "A transfer service tracks chunks", 10),
      edge(["service"], ["queue"], "Scan jobs are enqueued on completion", 10),
      biEdge(["queue"], ["worker"], "Scanners consume the queue", 10),
      node(["worker"], "Workers run the virus scan", 10),
      edge(["worker", "service"], ["nosql", "sql"], "Manifest and scan results are stored", 10),
      node(["cdn"], "Clean files are downloaded from the edge", 10),
      edge(["client"], ["cdn"], "Downloads come off the CDN", 10),
      node(["monitor"], "Stuck and infected uploads alert", 5),
    ],
  },
  {
    id: "tenant-gateway",
    category: "Infrastructure",
    name: "Multi-tenant API gateway",
    brief:
      "Hundreds of tenants share one platform; one tenant's burst must not become everyone's outage.",
    budget: 12,
    checks: [
      node(["client"], "Tenants call with their own keys", 5),
      node(["gateway"], "A gateway enforces per-tenant policy", 20),
      edge(["client"], ["gateway"], "All traffic passes the gateway", 10),
      node(["auth"], "Tenant identity is established at the edge", 10),
      node(["cache"], "Per-tenant quota state is shared and fast", 15),
      edge(["gateway"], ["cache"], "Quota checks read the cache", 10),
      edge(["gateway"], ["service"], "Admitted traffic reaches services", 10),
      edge(["service"], ["sql", "nosql"], "Tenant config lives in a database", 10),
      node(["monitor"], "Noisy-neighbor signals alert per tenant", 10),
    ],
  },
];

const MOBILITY = [
  {
    id: "ride-dispatch",
    category: "Mobility & Logistics",
    name: "Ride dispatch",
    brief:
      "Match riders to nearby drivers in seconds, under city-wide surge, without double-assigning a driver.",
    budget: 15,
    checks: [
      node(["client"], "Riders request, drivers accept", 5),
      edge(["client"], ["gateway", "lb"], "Requests enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A dispatch service owns matching", 10),
      node(["cache"], "Driver positions and availability live in memory", 15),
      edge(["service"], ["cache"], "Matching reads geo state from the cache", 10),
      node(["queue"], "Requests are serialized per zone for fairness", 10),
      edge(["service"], ["queue"], "Dispatch goes through the queue", 10),
      biEdge(["queue"], ["worker"], "Matcher workers assign exactly once", 10),
      edge(["worker"], ["sql", "nosql"], "Assignments are persisted", 10),
      node(["monitor"], "Match latency and surge are watched", 10),
    ],
  },
  {
    id: "parcel-tracking",
    category: "Mobility & Logistics",
    name: "Parcel tracking",
    brief:
      "Carrier scans arrive in bursts; customers refresh constantly. A stale-but-fast status beats a fresh-but-down page.",
    budget: 13,
    checks: [
      node(["client"], "Customers refresh tracking pages", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A tracking service fronts the data", 10),
      edge(["service"], ["queue"], "Carrier scans are buffered", 15),
      biEdge(["queue"], ["worker"], "Workers apply scan events", 10),
      edge(["worker"], ["nosql", "sql"], "Scan history is appended", 15),
      node(["cache"], "Latest status is cached for reads", 15),
      edge(["service"], ["cache"], "Page reads hit the cache", 10),
      node(["monitor"], "Scan-to-visible lag is measured", 10),
    ],
  },
  {
    id: "fleet-telemetry",
    category: "Mobility & Logistics",
    name: "Fleet telemetry ingest",
    brief:
      "Ten thousand vehicles report every few seconds. Ingest is relentless; queries are rare but heavy.",
    budget: 12,
    checks: [
      node(["client"], "Vehicles stream telemetry", 5),
      edge(["client"], ["gateway", "lb"], "Telemetry enters through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An ingest tier validates frames", 10),
      edge(["service"], ["queue"], "Frames are enqueued immediately", 20),
      node(["queue"], "The queue smooths constant pressure", 10),
      biEdge(["queue"], ["worker"], "Consumers write at their own pace", 10),
      edge(["worker"], ["nosql", "sql"], "Telemetry lands in a time-series store", 15),
      edge(["service"], ["nosql", "sql"], "Analysts query the store", 10),
      node(["monitor"], "Ingest lag is watched", 10),
    ],
  },
  {
    id: "eta-service",
    category: "Mobility & Logistics",
    name: "ETA computation",
    brief:
      "ETAs are expensive to compute and requested constantly; the same route segments repeat all day.",
    budget: 11,
    checks: [
      node(["client"], "Every screen shows an ETA", 5),
      edge(["client"], ["gateway", "lb"], "Traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "An ETA service answers", 10),
      node(["cache"], "Computed segments are memoized", 25),
      edge(["service"], ["cache"], "The hot path reads the cache", 15),
      edge(["service"], ["nosql", "sql"], "Road graph truth lives in a store", 10),
      node(["worker"], "Traffic models refresh in the background", 10),
      edge(["worker"], ["cache"], "Refreshed models update the cache", 10),
      node(["monitor"], "ETA accuracy is tracked", 5),
    ],
  },
  {
    id: "surge-pricing",
    category: "Mobility & Logistics",
    name: "Surge pricing",
    brief:
      "Demand signals stream in; multipliers update per zone every few seconds and are read on every fare quote.",
    budget: 12,
    checks: [
      node(["client"], "Every quote reads the multiplier", 5),
      edge(["client"], ["gateway", "lb"], "Quote traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "A pricing service serves quotes", 10),
      node(["queue"], "Demand signals stream through a queue", 15),
      biEdge(["queue"], ["worker"], "Aggregators consume the stream", 10),
      edge(["worker"], ["cache"], "Zone multipliers are published to memory", 15),
      node(["cache"], "Multipliers live in a fast store", 10),
      edge(["service"], ["cache"], "Quotes read the cache", 10),
      edge(["worker"], ["sql", "nosql"], "Pricing history is archived", 5),
      node(["monitor"], "Multiplier swings are observable", 10),
    ],
  },
  {
    id: "slot-booking",
    category: "Mobility & Logistics",
    name: "Delivery slot booking",
    brief:
      "Limited delivery slots per neighborhood; everyone books Sunday evening. No overbooking, fair ordering.",
    budget: 13,
    checks: [
      node(["client"], "Customers book delivery slots", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      node(["auth"], "Bookings are authenticated", 5),
      edge(["gateway", "lb", "auth"], ["service"], "A booking service owns slots", 10),
      node(["queue"], "Bookings are serialized per slot", 15),
      edge(["service"], ["queue"], "Requests are enqueued, not raced", 10),
      biEdge(["queue"], ["worker"], "A consumer applies bookings in order", 10),
      edge(["worker"], ["sql"], "Slot capacity is transactional", 15),
      node(["cache"], "Availability reads come from cache", 10),
      node(["monitor"], "Sunday-evening contention is visible", 10),
    ],
  },
  {
    id: "route-cache",
    category: "Mobility & Logistics",
    name: "Route memoization",
    brief:
      "The third-party routing API bills per call; your traffic repeats the same origin-destination pairs endlessly.",
    budget: 10,
    checks: [
      node(["client"], "Apps request routes", 5),
      edge(["client"], ["gateway", "lb"], "Traffic is load-balanced", 10),
      edge(["gateway", "lb"], ["service"], "A routing facade answers", 10),
      node(["cache"], "Computed routes are memoized aggressively", 30),
      edge(["service"], ["cache"], "The facade checks the cache first", 20),
      edge(["service"], ["nosql", "sql"], "Popular pairs are precomputed and stored", 10),
      node(["monitor"], "Upstream spend per hour is watched", 15),
    ],
  },
  {
    id: "driver-onboarding",
    category: "Mobility & Logistics",
    name: "Driver onboarding",
    brief:
      "License checks, background checks, vehicle photos — a multi-day pipeline with humans in the loop.",
    budget: 14,
    checks: [
      node(["client"], "Applicants upload documents", 5),
      edge(["client"], ["gateway", "lb"], "Uploads enter through a managed edge", 10),
      node(["auth"], "Applicant sessions are authenticated", 10),
      edge(["gateway", "lb", "auth"], ["service"], "An onboarding service tracks state", 10),
      edge(["service"], ["sql", "nosql"], "The application record is durable from step one", 10),
      edge(["service"], ["queue"], "Verification steps run async", 15),
      node(["queue"], "The pipeline survives multi-day waits", 5),
      biEdge(["queue"], ["worker"], "Verification workers process steps", 10),
      edge(["worker"], ["sql", "nosql"], "Step results append to the record", 15),
      node(["monitor"], "Pipeline stage times are visible", 10),
    ],
  },
  {
    id: "geofence-alerts",
    category: "Mobility & Logistics",
    name: "Geofence alerts",
    brief:
      "\"Your driver is nearby\" — location events tested against thousands of fences, notifications within seconds.",
    budget: 13,
    checks: [
      node(["client"], "Drivers emit locations, customers get alerts", 5),
      edge(["client"], ["gateway", "lb"], "Locations enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An ingest service validates events", 10),
      node(["queue"], "Location events stream through a queue", 15),
      biEdge(["queue"], ["worker"], "Fence evaluators consume the stream", 10),
      node(["worker"], "Workers test events against fences", 10),
      edge(["worker"], ["cache"], "Fence definitions are kept hot", 10),
      node(["cache"], "Fence lookups never hit the database", 10),
      edge(["worker"], ["nosql", "sql"], "Trigger history is recorded", 10),
      node(["monitor"], "Event-to-alert latency is measured", 10),
    ],
  },
  {
    id: "warehouse-scans",
    category: "Mobility & Logistics",
    name: "Warehouse scan bursts",
    brief:
      "Shift start floods the system with barcode scans. Each adjusts inventory exactly once, in order per SKU.",
    budget: 12,
    checks: [
      node(["client"], "Scanners fire at shift start", 5),
      edge(["client"], ["gateway", "lb"], "Scans enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An intake service validates scans", 10),
      edge(["service"], ["queue"], "Scans are enqueued per SKU", 20),
      node(["queue"], "The queue absorbs the shift-start flood", 10),
      biEdge(["queue"], ["worker"], "Workers apply scans in order", 10),
      edge(["worker"], ["sql"], "Inventory adjustments are transactional", 15),
      node(["cache"], "SKU lookups are cached", 10),
      node(["monitor"], "Scan backlog is visible on the floor", 10),
    ],
  },
];

const GAMING = [
  {
    id: "leaderboard",
    category: "Gaming",
    name: "Global leaderboard",
    brief:
      "Millions of score submissions; top-100 and your-rank queries on every screen. Sorted reads must be instant.",
    budget: 11,
    checks: [
      node(["client"], "Players submit and read scores", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A leaderboard service owns scores", 10),
      node(["cache"], "Rankings live in sorted in-memory structures", 25),
      edge(["service"], ["cache"], "Reads and rank updates hit the cache", 15),
      node(["queue"], "Score events stream out for durability", 10),
      node(["worker"], "A flusher reconciles to the store", 5),
      edge(["worker"], ["sql", "nosql"], "Scores are durable for season resets", 10),
      node(["monitor"], "Submission spikes are watched", 10),
    ],
  },
  {
    id: "matchmaking",
    category: "Gaming",
    name: "Skill matchmaking",
    brief:
      "Players wait in a pool while the system finds fair matches. Wait time and fairness trade off in real time.",
    budget: 13,
    checks: [
      node(["client"], "Players queue for matches", 5),
      edge(["client"], ["gateway"], "Connections terminate at an edge gateway", 10),
      edge(["gateway"], ["service"], "A matchmaking service owns the pool", 10),
      node(["queue"], "The player pool is a queue", 20),
      edge(["service"], ["queue"], "Joins are enqueued", 10),
      biEdge(["queue"], ["worker"], "Matcher workers scan the pool", 10),
      node(["worker"], "Workers balance fairness against wait time", 10),
      edge(["worker"], ["sql", "nosql"], "Match records are persisted", 10),
      node(["cache"], "Skill ratings are kept hot", 5),
      node(["monitor"], "Wait time percentiles are watched", 10),
    ],
  },
  {
    id: "game-telemetry",
    category: "Gaming",
    name: "Gameplay telemetry",
    brief:
      "Every match emits thousands of events for balance tuning. Lossy is fine for analytics — lossless for purchases.",
    budget: 12,
    checks: [
      node(["client"], "Game clients emit events", 5),
      edge(["client"], ["gateway", "lb"], "Events enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A collector batches events", 10),
      edge(["service"], ["queue"], "Events are enqueued immediately", 20),
      node(["queue"], "The queue rides out match-end spikes", 10),
      biEdge(["queue"], ["worker"], "Consumers drain at their own pace", 10),
      edge(["worker"], ["nosql"], "Events land in an analytical store", 15),
      edge(["service"], ["nosql", "sql"], "Designers query aggregates", 10),
      node(["monitor"], "Ingest lag is visible", 10),
    ],
  },
  {
    id: "daily-rewards",
    category: "Gaming",
    name: "Daily reward claims",
    brief:
      "Reset at midnight; everyone claims at 00:00:01. Exactly one reward per player per day.",
    budget: 13,
    checks: [
      node(["client"], "Players claim at midnight", 5),
      edge(["client"], ["gateway", "lb"], "The claim spike enters at the edge", 10),
      node(["auth"], "Claims are authenticated per player", 10),
      edge(["gateway", "lb", "auth"], ["service"], "A rewards service owns claims", 10),
      node(["queue"], "Claims are serialized for idempotency", 15),
      edge(["service"], ["queue"], "Claims are enqueued, not raced", 10),
      biEdge(["queue"], ["worker"], "A consumer grants exactly once", 10),
      edge(["worker"], ["sql"], "Grants are transactional per player-day", 15),
      node(["cache"], "Already-claimed checks come from cache", 5),
      node(["monitor"], "The midnight spike is watched live", 10),
    ],
  },
  {
    id: "ingame-store",
    category: "Gaming",
    name: "In-game store",
    brief:
      "Real-money purchases grant virtual items: provider charges, entitlement writes, and receipts that survive audits.",
    budget: 17,
    checks: [
      node(["client"], "Players buy items", 5),
      edge(["client"], ["gateway", "lb"], "Purchases enter through a managed edge", 10),
      node(["auth"], "Purchases are authenticated", 10),
      edge(["gateway", "lb", "auth"], ["service"], "A store service owns the flow", 10),
      edge(["service"], ["psp"], "The server calls the payment provider", 15),
      edge(["psp"], ["service", "queue", "worker"], "Provider confirmations arrive async", 10),
      node(["queue"], "Entitlement grants are buffered", 5),
      biEdge(["queue"], ["worker"], "Workers grant entitlements", 10),
      edge(["worker", "service"], ["sql"], "Entitlements and receipts are transactional", 15),
      node(["monitor"], "Failed grants after charge alert loudly", 10),
    ],
  },
  {
    id: "anti-cheat",
    category: "Gaming",
    name: "Anti-cheat pipeline",
    brief:
      "Match events analyzed for impossible play; bans must be reviewable with full evidence.",
    budget: 13,
    checks: [
      node(["client"], "Match servers stream events", 5),
      edge(["client"], ["gateway", "lb"], "Events enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An intake tier batches events", 10),
      edge(["service"], ["queue"], "Analysis jobs are enqueued", 15),
      node(["queue"], "The queue holds the analysis backlog", 10),
      biEdge(["queue"], ["worker"], "Analyzers consume the stream", 10),
      node(["worker"], "Detectors flag impossible play", 10),
      edge(["worker"], ["nosql", "sql"], "Evidence is preserved for review", 15),
      node(["monitor"], "False-positive rates are tracked", 15),
    ],
  },
  {
    id: "save-sync",
    category: "Gaming",
    name: "Cross-device save sync",
    brief:
      "Pick up on your phone where the console left off. Conflicts resolve deterministically — last-write-wins is not enough.",
    budget: 12,
    checks: [
      node(["client"], "Multiple devices sync saves", 5),
      edge(["client"], ["gateway", "lb"], "Sync traffic enters at the edge", 10),
      node(["auth"], "Saves are tied to an authenticated account", 10),
      edge(["gateway", "lb", "auth"], ["service"], "A sync service owns versions", 10),
      edge(["service"], ["nosql", "sql"], "Versioned saves are persisted", 20),
      node(["queue"], "Conflicts are resolved asynchronously", 5),
      node(["worker"], "A resolver merges divergent saves", 10),
      node(["cache"], "Latest-version pointers are cached", 10),
      edge(["service"], ["cache"], "Sync checks read the cache", 10),
      node(["monitor"], "Conflict rates are observable", 10),
    ],
  },
  {
    id: "tournaments",
    category: "Gaming",
    name: "Tournament brackets",
    brief:
      "Bracket updates fan out to every spectator the moment a match ends.",
    budget: 12,
    checks: [
      node(["client"], "Spectators watch live brackets", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A bracket service serves state", 10),
      node(["queue"], "Match results flow through a queue", 10),
      biEdge(["queue"], ["worker"], "Workers advance the bracket", 10),
      edge(["worker"], ["cache"], "The live bracket is published to memory", 15),
      node(["cache"], "Spectator reads come from cache", 10),
      edge(["service"], ["cache"], "The service reads the live bracket", 10),
      edge(["worker"], ["sql", "nosql"], "Bracket history is persisted", 10),
      node(["monitor"], "Result-to-visible latency is measured", 10),
    ],
  },
  {
    id: "lobby-chat",
    category: "Gaming",
    name: "In-game lobby chat",
    brief:
      "Low-stakes chat with moderation hooks and short retention.",
    budget: 12,
    checks: [
      node(["client"], "Players chat in lobbies", 5),
      edge(["client"], ["gateway"], "Connections terminate at an edge gateway", 15),
      edge(["gateway"], ["service"], "A chat service routes messages", 10),
      node(["queue"], "Messages flow through a queue for moderation hooks", 10),
      edge(["service"], ["queue"], "Sends are enqueued", 10),
      biEdge(["queue"], ["worker"], "Workers deliver and screen", 10),
      edge(["worker"], ["nosql", "sql"], "Short-retention history is stored", 10),
      node(["cache"], "Recent messages are cached for joins", 10),
      edge(["service"], ["cache"], "Joins read recent history fast", 10),
      node(["monitor"], "Delivery latency is watched", 10),
    ],
  },
  {
    id: "season-progress",
    category: "Gaming",
    name: "Season pass progression",
    brief:
      "XP events from every match update progression tracks; players check progress obsessively.",
    budget: 13,
    checks: [
      node(["client"], "Players earn and check progress", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A progression service owns tracks", 10),
      node(["queue"], "XP events stream through a queue", 15),
      edge(["service"], ["queue"], "Match ends enqueue XP", 10),
      biEdge(["queue"], ["worker"], "Workers apply progression", 10),
      edge(["worker"], ["sql", "nosql"], "Progress is durable", 10),
      node(["cache"], "Progress reads come from cache", 15),
      edge(["service"], ["cache"], "The check-progress path is cached", 10),
      node(["monitor"], "Apply lag is measured", 5),
    ],
  },
];

const SAAS = [
  {
    id: "audit-log",
    category: "B2B SaaS",
    name: "Tenant audit log",
    brief:
      "Every admin action recorded append-only; auditors export years of history without affecting the product.",
    budget: 12,
    checks: [
      node(["client"], "Admin actions generate events", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      node(["auth"], "Actor identity is verified", 10),
      edge(["gateway", "lb", "auth"], ["service"], "Product services emit audit events", 10),
      edge(["service"], ["queue"], "Events are enqueued, never block the action", 10),
      node(["queue"], "The queue guarantees capture", 10),
      biEdge(["queue"], ["worker"], "Writers consume the stream", 10),
      edge(["worker"], ["sql"], "Entries are append-only and transactional", 20),
      edge(["service"], ["sql"], "Auditors query and export history", 5),
      node(["monitor"], "Write failures alert immediately", 10),
    ],
  },
  {
    id: "usage-metering",
    category: "B2B SaaS",
    name: "Usage metering",
    brief:
      "Billable events must be counted exactly once — undercounting burns revenue, overcounting burns trust.",
    budget: 13,
    checks: [
      node(["client"], "Product surfaces emit billable events", 5),
      edge(["client"], ["gateway", "lb"], "Events enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A metering service deduplicates", 10),
      edge(["service"], ["queue"], "Events are enqueued with idempotency keys", 20),
      node(["queue"], "The queue is the at-least-once boundary", 10),
      biEdge(["queue"], ["worker"], "Aggregators consume exactly-once", 10),
      edge(["worker"], ["sql"], "Counters are transactional per tenant", 15),
      node(["cache"], "Current-period usage is readable fast", 5),
      node(["monitor"], "Count drift is reconciled and alerted", 15),
    ],
  },
  {
    id: "bulk-import",
    category: "B2B SaaS",
    name: "Tenant bulk import",
    brief:
      "Customers upload million-row CSVs and watch a progress bar. Validation errors arrive as a report, not a timeout.",
    budget: 13,
    checks: [
      node(["client"], "Customers upload CSVs", 5),
      edge(["client"], ["gateway", "lb"], "Uploads enter through a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "An import service accepts files", 10),
      edge(["service"], ["queue"], "Import jobs are enqueued", 15),
      node(["queue"], "Batch work is isolated from the app", 5),
      biEdge(["queue"], ["worker"], "Import workers chew through rows", 10),
      node(["worker"], "Workers validate and report per row", 10),
      edge(["worker"], ["sql", "nosql"], "Rows and error reports are persisted", 15),
      node(["cache"], "Progress state is readable live", 10),
      node(["monitor"], "Stuck imports are visible", 10),
    ],
  },
  {
    id: "job-scheduler",
    category: "B2B SaaS",
    name: "Scheduled jobs platform",
    brief:
      "Tenants schedule recurring tasks; missing a run is a support ticket, running twice is a bug report.",
    budget: 11,
    checks: [
      node(["client"], "Tenants manage schedules", 5),
      edge(["client"], ["gateway", "lb"], "The API sits behind a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A scheduler service owns definitions", 10),
      node(["queue"], "Due jobs are enqueued exactly once", 20),
      biEdge(["queue"], ["worker"], "Runners consume due jobs", 15),
      node(["worker"], "Workers execute tenant tasks", 10),
      edge(["worker"], ["sql"], "A run ledger records every execution", 15),
      node(["monitor"], "Missed and duplicate runs alert", 15),
    ],
  },
  {
    id: "doc-search",
    category: "B2B SaaS",
    name: "Tenant document search",
    brief:
      "Full-text search across each tenant's documents, isolated per tenant, index fresh within a minute.",
    budget: 13,
    checks: [
      node(["client"], "Users search their documents", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      node(["auth"], "Tenant isolation starts with identity", 10),
      edge(["gateway", "lb", "auth"], ["service"], "A search API scopes queries per tenant", 10),
      edge(["service"], ["nosql", "sql"], "Queries hit the index store", 15),
      node(["queue"], "Document changes stream to the indexer", 10),
      node(["worker"], "An indexer applies changes", 10),
      edge(["worker"], ["nosql", "sql"], "The index updates incrementally", 10),
      node(["cache"], "Hot queries are cached per tenant", 10),
      node(["monitor"], "Index freshness is measured", 10),
    ],
  },
  {
    id: "scim-sync",
    category: "B2B SaaS",
    name: "SCIM user provisioning",
    brief:
      "Enterprise IdPs push joiner/mover/leaver events; access must revoke within minutes, with an audit trail.",
    budget: 13,
    checks: [
      node(["client"], "IdPs push SCIM events", 5),
      edge(["client"], ["gateway", "lb"], "Events enter through a managed edge", 10),
      node(["auth"], "Provisioning is itself authenticated", 15),
      edge(["gateway", "lb"], ["service"], "A provisioning service accepts events", 10),
      edge(["service"], ["queue"], "Events are enqueued for ordered apply", 15),
      node(["queue"], "Ordering matters: leaver after joiner", 10),
      biEdge(["queue"], ["worker"], "Workers apply identity changes", 10),
      edge(["worker"], ["sql"], "Identity state and audit trail are transactional", 15),
      node(["monitor"], "Revocation latency alerts past SLA", 10),
    ],
  },
  {
    id: "email-campaigns",
    category: "B2B SaaS",
    name: "Email campaign sender",
    brief:
      "A million-recipient send is a marathon: throttled per provider, bounces handled, unsubscribes instant.",
    budget: 13,
    checks: [
      node(["client"], "Marketers launch campaigns", 5),
      edge(["client"], ["gateway", "lb"], "The app sits behind a managed edge", 10),
      edge(["gateway", "lb"], ["service"], "A campaign service owns sends", 10),
      edge(["service"], ["queue"], "Recipients are enqueued in batches", 20),
      node(["queue"], "The queue is the throttle point", 10),
      biEdge(["queue"], ["worker"], "Sender workers drain within rate limits", 10),
      node(["worker"], "Workers handle bounces and retries", 10),
      edge(["worker"], ["sql", "nosql"], "Send state and suppressions are persisted", 10),
      node(["monitor"], "Bounce and complaint rates alert", 15),
    ],
  },
  {
    id: "tenant-billing",
    category: "B2B SaaS",
    name: "Tenant billing & invoicing",
    brief:
      "Metered usage becomes a monthly invoice and a card charge. Disputes need line-item provenance.",
    budget: 17,
    checks: [
      node(["client"], "Tenants view invoices", 5),
      edge(["client"], ["gateway", "lb"], "The billing UI sits behind a managed edge", 10),
      node(["service"], "A billing service owns the cycle", 5),
      node(["queue"], "The billing run is a queue of tenant jobs", 10),
      biEdge(["queue"], ["worker"], "Billing workers process tenants", 10),
      node(["worker"], "Workers compute invoices from usage", 10),
      edge(["worker"], ["psp"], "Charges go through the payment provider", 15),
      edge(["psp"], ["service", "worker", "queue"], "Provider confirmations arrive async", 10),
      edge(["worker"], ["sql"], "Invoices and line items are transactional", 15),
      node(["monitor"], "Failed charges and stuck runs alert", 10),
    ],
  },
  {
    id: "crm-sync",
    category: "B2B SaaS",
    name: "Two-way CRM sync",
    brief:
      "Your app and the customer's CRM both edit the same records; sync both ways without loops or lost updates.",
    budget: 13,
    checks: [
      node(["client"], "Both sides edit records", 5),
      edge(["client"], ["gateway", "lb"], "Webhooks and edits enter at the edge", 10),
      edge(["gateway", "lb"], ["service"], "A sync service owns the mapping", 10),
      edge(["service"], ["queue"], "Changes are enqueued with provenance", 15),
      node(["queue"], "Ordered processing prevents loops", 10),
      biEdge(["queue"], ["worker"], "The sync engine applies changes", 10),
      node(["worker"], "Workers detect echoes and conflicts", 10),
      edge(["worker"], ["sql", "nosql"], "Mapping and cursor state are persisted", 15),
      node(["monitor"], "Sync lag and conflict rates are visible", 10),
      node(["cache"], "Mapping lookups are cached", 5),
    ],
  },
  {
    id: "tenant-analytics",
    category: "B2B SaaS",
    name: "Tenant analytics dashboards",
    brief:
      "Every tenant wants charts over their own data; one tenant's heavy query can't slow the others.",
    budget: 12,
    checks: [
      node(["client"], "Tenant admins load dashboards", 5),
      edge(["client"], ["gateway", "lb"], "Traffic enters through a managed edge", 10),
      node(["auth"], "Tenant scoping starts with identity", 10),
      edge(["gateway", "lb", "auth"], ["service"], "A query service scopes per tenant", 10),
      node(["cache"], "Repeated charts are cached per tenant", 15),
      edge(["service"], ["cache"], "Reads hit the cache first", 10),
      edge(["service"], ["nosql", "sql"], "The analytics store answers misses", 10),
      node(["worker"], "Rollups precompute the heavy queries", 10),
      edge(["worker"], ["nosql", "sql"], "Workers write rollups", 10),
      node(["monitor"], "Per-tenant query cost is visible", 10),
    ],
  },
];

/** @type {Scenario[]} */
export const SCENARIOS = [
  ...COMMERCE,
  ...FINTECH,
  ...SOCIAL,
  ...REALTIME,
  ...CONTENT,
  ...DATA,
  ...INFRA,
  ...MOBILITY,
  ...GAMING,
  ...SAAS,
];
