// Official docs / canonical reference per tech, shown when a quiz answer is revealed.
/** @type {Record<string, string>} */
export const techLinks = {
  TypeScript: "https://www.typescriptlang.org/docs/",
  JavaScript: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  Java: "https://docs.oracle.com/en/java/",
  PHP: "https://www.php.net/docs.php",
  Python: "https://docs.python.org/3/",
  "C++": "https://en.cppreference.com/w/",
  React: "https://react.dev/learn",
  "React Native": "https://reactnative.dev/docs/getting-started",
  "Next.js": "https://nextjs.org/docs",
  TanStack: "https://tanstack.com/query/latest/docs/framework/react/overview",
  Redux: "https://redux-toolkit.js.org/",
  Tailwind: "https://tailwindcss.com/docs",
  "Material UI": "https://mui.com/material-ui/getting-started/",
  Vite: "https://vite.dev/guide/",
  Rspack: "https://rspack.rs/guide/start/introduction",
  Webpack: "https://webpack.js.org/concepts/",
  "pnpm / Corepack": "https://pnpm.io/motivation",
  "Node.js": "https://nodejs.org/docs/latest/api/",
  NestJS: "https://docs.nestjs.com/",
  "GraphQL (Relay)": "https://graphql.org/learn/",
  "REST / OpenAPI": "https://swagger.io/specification/",
  Microservices: "https://microservices.io/patterns/index.html",
  "Auth & Security": "https://owasp.org/www-project-top-ten/",
  "Azure DevOps": "https://learn.microsoft.com/en-us/azure/devops/",
  "Azure Portal / GCP": "https://learn.microsoft.com/en-us/azure/",
  "CI/CD Pipelines": "https://learn.microsoft.com/en-us/azure/devops/pipelines/",
  Docker: "https://docs.docker.com/get-started/",
  Kubernetes: "https://kubernetes.io/docs/concepts/",
  Git: "https://git-scm.com/doc",
  "Application Insights": "https://learn.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview",
  KQL: "https://learn.microsoft.com/en-us/kusto/query/",
  Datadog: "https://docs.datadoghq.com/",
  Grafana: "https://grafana.com/docs/grafana/latest/",
  LaunchDarkly: "https://launchdarkly.com/docs",
  "GitHub Copilot": "https://docs.github.com/en/copilot",
  "Claude / OpenAI Codex": "https://docs.claude.com/en/docs/overview",
  "RAG Pipelines": "https://www.pinecone.io/learn/retrieval-augmented-generation/",
  "Playwright (E2E)": "https://playwright.dev/docs/intro",
  Jest: "https://jestjs.io/docs/getting-started",
  "React Testing Library": "https://testing-library.com/docs/react-testing-library/intro/",
  TDD: "https://martinfowler.com/bliki/TestDrivenDevelopment.html",
  "App Store / Play Store": "https://developer.apple.com/distribute/",
  PostgreSQL: "https://www.postgresql.org/docs/current/",
  MySQL: "https://dev.mysql.com/doc/",
  Oracle: "https://docs.oracle.com/en/database/",
  MongoDB: "https://www.mongodb.com/docs/manual/",
  Couchbase: "https://docs.couchbase.com/home/index.html",
  Redis: "https://redis.io/docs/latest/",
  SQLite: "https://www.sqlite.org/docs.html",
  HubSpot: "https://developers.hubspot.com/docs",
};
