-- Record quiz attempts and XP as one retry-safe operation. The request id is
-- generated by the client before mutation execution, so a repeated transport
-- attempt cannot insert another answer or award XP twice.

alter table answer_events add column request_id text;

create unique index answer_events_user_request_id
  on answer_events (user_id, request_id)
  where request_id is not null;

create or replace function record_answer(
  p_request_id text,
  p_tech text,
  p_correct boolean,
  p_source text,
  p_difficulty text
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  xp_points int;
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if p_request_id is null or btrim(p_request_id) = '' then
    raise exception 'Request id is required' using errcode = '23514';
  end if;

  insert into answer_events (user_id, tech, correct, source, difficulty, request_id)
  values (current_user_id, p_tech, p_correct, p_source, p_difficulty, p_request_id)
  on conflict (user_id, request_id) where request_id is not null do nothing;

  if not found or not p_correct then
    return;
  end if;

  xp_points := case p_difficulty
    when 'easy' then 5
    when 'high' then 20
    when 'ultra' then 40
    else 10
  end;

  insert into profiles (user_id, xp)
  values (current_user_id, xp_points)
  on conflict (user_id) do update set xp = profiles.xp + excluded.xp;
end;
$$;

create or replace function reset_scores()
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  delete from answer_events where user_id = current_user_id;
  insert into profiles (user_id, xp)
  values (current_user_id, 0)
  on conflict (user_id) do update set xp = 0;
end;
$$;

revoke all on function record_answer(text, text, boolean, text, text) from public;
revoke all on function reset_scores() from public;
grant execute on function record_answer(text, text, boolean, text, text) to authenticated;
grant execute on function reset_scores() to authenticated;
